# Generated by Django 3.0.6 on 2020-06-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='flexibility_after',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='flexibility_before',
        ),
    ]
